module.exports = {
  storeIndents        : str => str ? ' '.repeat(str.search(/\S/)) : '',
  isKeyValuePair      : arr => arr.length === 2,
  isSubselector       : str => str.charAt(1) === '&',
  convertSubselector  : str => str.replace(/[': {']+/g, ' {'),
  isHeader            : str => str.slice(-2) === '({',
  convertHeader       : str => [`[p.${str}, \``],
  toKebabCase         : str => str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase(),
  removeDoubleQuotes  : str => str.replace(/['"]+/g, ''),
  convertCommas       : str => str.slice(-1) === ',' ? `${str.slice(0, -1)};` : str,
  isResponsive        : str => str.includes('...oldResponsive'),
  convertResponsive   : str => `\${responsive.${str.match(/"((?:\\.|[^"\\])*)"/)[1]}\``,
  convertEndBrackets  : str => str.includes('})') ? '`}' : str,
  addMissingSemicolon : str => !str.includes(';') && !str.includes('{') ? `${str};` : str,
  addFinalBacktick    : str => str.includes('})') ? '`],' : str,
}